public class DNSHeader {

    //This class should store all the data provided by the 12 byte DNS header.
    //You'll probably need a few getters, but you should NOT provide any setters.

    //Since this is the first thing in a DNS request, you should be able to test that
    //you can read/decode the header before starting on other classes.

    
    //read the header from an input stream (we'll use a ByteArrayInputStream but we
    //will only use the basic read methods of input stream to read 1 byte, or to fill
    //in a byte array, so we'll be generic).
    static DNSHeader decodeHeader( InputStream) {

    }

    //This will create the header for the response. 
    //It will copy some fields from the request
    static DNSHeader buildResponseHeader( DNSMessage request, DNSMessage response) {

    }

    //Encode the header to bytes to be sent back to the client.
    //The OutputStream interface has methods to write a single byte or an array of bytes.
    void writeBytes (OutputStream) {

    }

    //Return a human readable string version of a header object.
    //A reasonable implementation can be autogenerated by your IDE.
    String toString() {

    }
    
}
